### ISSUE TITLE
Be brave and put some code here, how long should I have to wait

### ISSUE THREAD

**Issue by ramsafin** [VladMatyunin/robot_engineer#1]
<p>Vlad, you're the best, the coolest dude in the world. Let's do it!</p>

**Comment by VladMatyunin** [comment]
@chupakabra1996 You know, honey, I'm so beasy now, keep waiting, soon here will be nice stuff, think you'll like it! We had to fix some shit in university portal, it's desgausted me FUUUUUUCK!

**Comment by VladMatyunin** [comment]
@chupakabra1996 Done!
